
version: 2

sources:
  - name: powerflow
    database: POWERFLOW       # Убедись, что имя базы данных и схемы совпадают с тем, что в Snowflake
    schema: PUBLIC            # Замени, если используется другая схема
    tables:
      - name: registrations
      - name: google_ads
      - name: campaign_costs
      - name: appsflyer_raw
      - name: transactions

models:
  - name: registrations_clean
    columns: 
      - name: user_id
        tests: #tests that would be run on the column
          - unique
  - name: marketing_attribution 
    columns: 
      - name: device_id
        tests:
          - unique
          - not_null
      - name: attribution_cost
        tests:
          - not_null
  - name: ltv
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: roi
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi
        tests:
           - not_null      
