
version: 2

sources:
  - name: POWERFLOW
    database: POWERFLOW       # Убедись, что имя базы данных и схемы совпадают с тем, что в Snowflake
    schema: PUBLIC            # Замени, если используется другая схема
    tables:
      - name: registrations
      - name: google_ads
      - name: campaign_costs
      - name: appsflyer_raw
      - name: transactions



models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
